INSERT INTO `productos` (`codigo`, `nombre`, `descripcion`, `stock`, `precio`, `visible`) VALUES
(1, 'Masa', 'Masa', 1, 10, 'visible'),
(2, 'Salsa de tomate', '-', 10, 0, 'visible'),
(3, 'Queso hacienda', '-', 10, 0, 'visible'),
(4, 'Queso parmesano', 'En kilo', 10, 0, 'visible'),
(5, 'Tocino', 'En kilo', 9, 0, 'visible'),
(6, 'Pepperoni', '5 Kilos', 9, 0, 'visible'),
(7, 'Camarón', '-', 10, 0, 'visible'),
(8, 'Mantequilla', 'Kilo', 10, 0, 'visible'),
(9, 'Jamón', '-', 10, 0, 'visible'),
(10, 'Ajo', '-', 10, 0, 'visible'),
(11, 'Orégano', '-', 10, 0, 'visible'),
(12, 'Pepperoni', '-', 10, 0, 'visible'),
(13, 'Carne', '-', 10, 10, 'visible'),
(14, 'Cebolla', '-', 10, 0, 'visible'),
(15, 'Pollo', '-', 10, 0, 'visible'),
(16, 'Aceitunas', '-', 10, 0, 'visible'),
(17, 'Tomate cherry', '-', 10, 0, 'visible'),
(18, 'Champiñón', '-', 10, 0, 'visible'),
(19, 'Choclo', '-', 10, 0, 'visible'),
(20, 'Tocino', '-', 10, 0, 'visible'),
(21, 'Pimentón', '-', 10, 0, 'visible'),
(22, 'Jalapeño', '-', 10, 0, 'visible'),
(23, 'Chorizo', '-', 10, 0, 'visible'),
(24, 'Crema', '-', 10, 0, 'visible'),
(25, 'Sémola', '-', 10, 0, 'visible');


INSERT INTO `promociones` (`codigo`, `nombre`, `categoria`, `descripcion`, `precio`, `visible`) VALUES
(1, '01 PEPE IRONIC', 'Tus REGALONAS', 'Pepperoni y tocino', 9500, 'invisible'),
(2, '02 LA SIÚTICA', 'Tus REGALONAS', 'Lomo salteado, choclo y cebolla salteada', 9500, 'visible'),
(3, '03 LA GOLOSA', 'Tus REGALONAS', 'Pepperoni americano, pollo al curry, tocino ahumado y aceitunas', 11990, 'visible'),
(4, '04 LA DIABLA', 'Tus REGALONAS', 'Pollo al curry, cebolla salteada, tomate cherry, aceitunas y jalapeños', 9990, 'visible'),
(5, '05 LA TERRIBLE', 'Tus REGALONAS', 'Pollo al curry, cebolla salteada, choclo, pimentón asado y jalapeños', 11990, 'visible'),
(6, '06 LA CAVERNÍCOLA', 'Tus REGALONAS', 'Lomo salteado, pepperoni americano, aceitunas y tomate cherry', 9990, 'visible'),
(7, '07 LA CHORIZA', 'Tus REGALONAS', 'Chorizo de carne angus, cebolla salteada, aceitunas y pimentón asado', 10990, 'visible'),
(8, '08 CAPRICHICKEN', 'Tus REGALONAS', 'Pollo al curry, choclo y champiñón', 9500, 'visible'),
(9, '09 LA TRAVIESA', 'Tus REGALONAS', 'Pollo al orégano, choclo, champiñones y cebolla salteada', 9500, 'visible'),
(10, '10 LA CURIOSA', 'Tus REGALONAS', 'Tocino ahumado, champiñones y aceitunas', 9000, 'visible'),
(11, '11 LA TÓXICA', 'Tus REGALONAS', 'Tocino ahumado, lomo salteado, cebolla salteada y pimentón asado', 10990, 'visible'),
(12, '12 LA CUARENTONA', 'Tus REGALONAS', 'Pollo al curry, aceitunas negras, pimentón asado, jalapeños y cebolla salteada', 11990, 'visible'),
(13, '01 MERCURIO', 'Galácticas', 'Camarón ecuatoriano, pollo a la crema, choclo y champiñones', 11990, 'visible'),
(14, '02 VENUS', 'Galácticas', 'Pollo a la crema, jamón serrano, tomate cherry y pimentón salteado', 11990, 'visible'),
(15, '03 TERRÍCOLA', 'Galácticas', 'Aceitunas, cebolla salteada, pimentón salteado, champiñón y choclo', 11990, 'visible'),
(16, '04 MARTE', 'Galácticas', 'Lomo salteado, tocino americano, chorizo de carne angus y cebolla salteada', 12990, 'visible'),
(17, '05 JÚPITER', 'Galácticas', 'Pepperoni americano, tocino americano, jamón serrano y lomo salteado', 13990, 'visible'),
(18, '06 SATURNO', 'Galácticas', 'Jamón serrano, cebolla salteada, aceitunas y jalapeños', 12990, 'visible'),
(19, '07 URANO', 'Galácticas', 'Tocino americano, lomo salteado, cebolla salteada y pimentónn', 11990, 'visible'),
(20, '08 NEPTUNO', 'Galácticas', 'Pollo a la crema, tocino, pimentón asado y tomate cherry', 11990, 'visible'),
(21, '09 PLUTÓN', 'Galácticas', 'Pollo al orégano, lomo salteado, cebolla salteada y aceitunas', 11990, 'visible'),
(22, '10 SOLAR', 'Galácticas', 'Tocino, choclo, champiñones y cebolla salteada', 11990, 'visible'),
(23, '01 PAPAS EL CHAVO', 'Big box FRIES', 'Papas fritas cubiertas con pollo a la crema, cebolla salteada, pimentón y trilogía de quesos (mozzarella, parmesano y reggianito)', 13990, 'visible'),
(24, '02 PAPAS CHILINDRINA', 'Big box FRIES', 'Papas cubiertas con pollo a la crema, choclo, champiñón, y trilogía de quesos (mozzarella, parmesano y reggianito)', 13990, 'visible'),
(25, '03 PAPAS DOÑA FLORINDA', 'Big box FRIES', 'Papas cubiertas con lomo salteado, cebolla salteada, aceitunas, y trilogía de quesos (mozarella, parmesano y reggianito)', 13990, 'visible'),
(26, '04 PAPAS KIKO', 'Big box FRIES', 'Papas cubiertas con lomo salteado, pimentón, aceitunas, y trilogía de quesos (mozarella, parmesano y reggianito)', 13990, 'visible'),
(27, '05 PAPAS DON RAMÓN', 'Big box FRIES', 'Papas cubiertas con pollo a la crema, pimentón, champiñones, y trilogía de quesos (mozarella, parmesano y reggianito)', 13990, 'visible'),
(28, '06 SALCHIPAPAS', 'Big box FRIES', 'Papas fritas con vienesas', 6000, 'visible'),
(29, '5 Empanadas de queso', 'Extras', '5 unidades', 1690, 'visible'),
(30, '10 Empanadas de queso', 'Extras', '10 unidades', 2990, 'visible'),
(31, '8x Palitos de ajo', 'Extras', '8 unidades', 4990, 'visible'),
(32, 'Bebida en lata 350 ml', 'Bebidas', 'Coca cola, sprite, fanta', 1500, 'visible'),
(33, 'Bebida 2,5 lts', 'Bebidas', 'Coca cola, sprite, fanta', 3000, 'visible'),
(34, 'Alcaparras', 'Extras', '-', 1000, 'visible'),
(35, 'Jalapeños', 'Extras', '-', 1000, 'visible'),
(36, 'Salsa barbecue', 'Extras', '-', 1000, 'visible'),
(37, 'Bordes de queso', 'Otros', 'Agrega bordes de queso a tu pizza', 2990, 'visible'),
(38, 'Agranda tu pizza a XL', 'Otros', 'Agranda tu pizza', 2990, 'visible');

INSERT INTO `usuarios` (`rut`, `nombre_completo`, `email`, `password`, `direccion`, `telefono`, `rol`, `habilitacion`, `remember_token`) VALUES
('0-0', 'Admin Test', 'test@test.cl', '$2y$10$J3i10rhPW2cTVTLWzwF1Z.bXohccko3Z8l.6.c19ZSO1qlQvxhbZW', 'test', '0', 'administrador', 'habilitado', 'AXRjV5hI9ddKjMTSjkRh2XvAYdldQD2JeUiEUuxeyiZl2v3wXFeEdx56GF9O'),
('19278204-K', 'Vendedor2', 'vendedor2@test.cl', '$2y$10$4causSLJ0ol.9TpG9CA8jOpiWCvj64RYi0FivFyB80jgrEBzEvaje', 'Jenga\'s Pizza', '', 'vendedor', 'habilitado', NULL),
('19414244-7', 'Repartidor Test', 'reparto@test.cl', '$2y$10$Cb.Ey5PKzzKhbgWmBC8xD.4Jysbxbi9/Tim5TwGXtm2IFhA9kMLAC', 'Test', '0', 'repartidor', 'habilitado', NULL),
('19416137-9', 'jean gatica', 'jpgatica48@gmail.com', '$2y$10$16c8DjCuMBtJNBCKRERl0.26FwnwQqlKsfJyJengCcYGpID/gZUq6', 'av ohigins', '0', 'cliente', 'habilitado', NULL),
('19543720-3', 'Cocinero Test', 'cocinero@test.cl', '$2y$10$8v6DQWUC63po.Xktk2jXCesDde.mJcDecxZSHf3WjGH9cHw7cuNZ2', 'Local Jenga\'s Pizza', '0', 'cocinero', 'habilitado', NULL);
